### ISSUE TITLE
I have problems in section "Calling Funtion" (https://youtu.be/ZNDZuT9hmNo?t=25713)

### ISSUE THREAD

**Issue by tansitrinh2811** [mistertandon/web3-project-023-uniswap-clone-part-iv#1]
Hi sir
You and I are both working on the same project that looks quite similar, "UNISWAP_CLONE"
Please help me fix my bug 
Everything was fine until I started the "CALLING FUNTION" phase.
My code is still running fine, it's just that the swap function from ether to dai (not to mention other tokens) is not okay
The error I encountered was related to this code:
![image](https://github.com/mistertandon/web3-project-023-uniswap-clone-part-iv/assets/76555798/071ee9b5-0f9c-4bda-8d27-a98665814051)
When I run it on the client, it still runs normally but does not show the price of token2
...
Unhandled Runtime Error
TypeError: Cannot destructure property 'token1' of 'param' as it is undefined.

Source
Context\SwapContext.js (112:33) @ soloSwapToken

  110 | }, [])
  111 | //SOLO SWAP TOKEN
> 112 | const soloSwapToken = async({token1, token2, swapAmount}) =>{
      |                             ^
  113 |     console.log(token1.tokenAddress.tokenAddress, token2.tokenAddress.tokenAddress, swapAmount)
  114 |     try {
  115 |         let soloSwapToken

On the client side, I can run the remaining segments, but the result in the second token is not available
![image](https://github.com/mistertandon/web3-project-023-uniswap-clone-part-iv/assets/76555798/5c301e8e-2250-4d53-a275-46fdbb428919)
Hope you can help me, I really need this project

**Comment by mistertandon** [comment]
Hi Tan,
I sincerely apologize for such late reply but somehow I missed GitHub notification.

In browser console I can observe error message `window.ethereum is not found`. This error message is specific to metamask wallet availability. Could you please check If you have access to Metamask wallet in the same browser.

Let's connect over a short Microsoft Team call and debug the issue.

Thank you
